language: csharp
solution: Com.Latipium.Website.Apis.sln
install:
- nuget restore
mono:
- latest
deploy:
  provider: script
  script: ./deploy.sh
  skip_cleanup: true
cache:
  directories:
    - packages/
